### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by tkodev** [stefanjudis/forrest#116]
<img width="532" alt="screen shot 2017-06-30 at 2 57 35 pm" src="https://user-images.githubusercontent.com/4338187/27750155-972071f0-5da4-11e7-828f-30c29bef4991.png">

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'getDisplayMatching' of null
    at Timeout.updateState [as _onTimeout] (/Applications/Forrest.app/Contents/Resources/app/node_modules/electron-window-state/index.js:62:33)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
Not sure why I get this, but it happened when I first ran a command and after a closed a forrest terminal window

**Comment by stefanjudis** [comment]
@htkoca Hmm... is this reproducable? I just tried it a bit and am not sure how you reached it.

I assume you're also on the latest version?

**Comment by tkodev** [comment]
Hmm, I'd like to find out as well. Currently on node 7.9.0 & npm 5 (if that
matters?) and latest version of forrest. I do electron / node dev somewhat, will
global packages / environment variables affect it? I'll take a look at the
source tonight

**Comment by tkodev** [comment]
edit: I've been using forrest all day and haven't encountered the error. Perhaps it is my environment? Note - I've switched back to node 7.9.0, npm 4.2.0. Not sure if it changes anything.

**Comment by stefanjudis** [comment]
Hmm... okay. 

It shouldn't be related to your local version. As electron ships with its own node. but yeah. gald that it's not appearing anymore. :)
