### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [stefanjudis/forrest#121]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by stefanjudis** [comment]
Hey Daniel,

well... last commit was three years ago, so I wouldn't say so. :/

Would you be up for contributing? 😊

**Comment by DanielRuf** [comment]
I can contribute some time like updating dependencies, improving code quality, writing PRs for some issues and so on.

But it's probably better to move the project to an org account for better rights management and so on.

**Comment by DanielRuf** [comment]
What do you think?

**Comment by stefanjudis** [comment]
Wooohoooooo! :) 

Yeah, I don't mind creating a `forrest` org and move it there as `forrest-app`. Neutral ownership is often better. :)

Can do tmrw! And will invite you. :)

**Comment by stefanjudis** [comment]
I moved the repo and invited you to the org. :)
