### ISSUE TITLE
Make it possible to define custom commands in settings area

### ISSUE THREAD

**Issue by danez** [stefanjudis/forrest#16]
Would be nice to have these two available.

or a single button that is doing

```
npm version <>
npm publish
git push --follow-tags
```

Or even better have some kind of "create your own tasks", where people can add there own commands.

**Comment by stefanjudis** [comment]
Jup. Totally agree.

But I'm more thinking of a way to add commands into the settings section.
Something like `publish` which does exactly that... 

Would it be okay, to have a customizable area to add your specific command combinations? :)

**Comment by danez** [comment]
Haha, I was just editing my post and added the same idea 👍
