### ISSUE TITLE
Forrest cannot be closed from mac menu

### ISSUE THREAD

**Issue by danez** [stefanjudis/forrest#28]
When I press close nothing happens.
![bildschirmfoto 2016-07-25 um 14 10 43](https://cloud.githubusercontent.com/assets/231804/17100891/97e84372-5271-11e6-9b19-a88402cdf163.png)

**Comment by stefanjudis** [comment]
Hmm... works fine here. 

Could you start the app with the binary

```
$ ./.../.../.../Forrest.app/Contents/MacOS/Forrest 
```

and check if some exceptions occur?

**Comment by danez** [comment]
It works when I start it this way, but not when starting it from the Applications folder by clicking on Forrest.app or on the pinned shortcut in the dock.

Also clicking on the x on the left top of the window, closes the window, but does not close the app. And then there is no way to bring back the window, without forceclosing and reopening.

**Comment by stefanjudis** [comment]
Hmm... Did the same. Still works. 
No idea how to approach that. :(

**Comment by danez** [comment]
Hmm, so i tried downloading the zip and the dmg both do not work for me. Also putting the forrest.app not in /Applications/ but somewhere else does not change anything.

I tried removing ~/Library/Application Support/Forrest which removed all my projects and settings but still not working.

Maybe its the node version?
node v4.4.7
npm 3.10.6

Node is installed via nvm and nvm is installed via homebrew.
macOS is at the latest version 10.11.6

**Comment by stefanjudis** [comment]
Okay... Updating OS then today... :D That's the only thing that could matter here. 

node and npm shouldn't make any difference as electron (and the app) ships with its own node.

**Comment by danez** [comment]
For the second problem that after closing the main window I cannot bring back the window this might help: https://github.com/mattermost/desktop/blob/master/src/main.js#L161
Maybe also the event handling for the other events helps, but never worked with electron before.

**Comment by stefanjudis** [comment]
> For the second problem that after closing the main window I cannot bring back the window this might help:

works here as well. Let's see if I can reproduce when I'm on the same os version.

**Comment by stefanjudis** [comment]
@danez Can you please check if the problem still appears in `v1.0.0-beta`?

**Comment by danez** [comment]
I just tried on a different computer.
The initial test today was on a Macbook Pro 13' Retina 2015
Now I tested on Macbook Pro 15' 2010, with the same problem. :(

Both have 10.11.6

**Comment by stefanjudis** [comment]
damn it... yeah, I'll dig the electron bug tracker the next days. but here it's still running perfectly fine.

![macosbug](https://cloud.githubusercontent.com/assets/962099/17117747/e98097ce-52bd-11e6-9076-b95a5cd434ad.gif)

**Comment by stefanjudis** [comment]
@danez is this still an issue?

**Comment by danez** [comment]
Yes thanks, delta solves the problem 🎉
