### ISSUE TITLE
Window too small on initial start after first install

### ISSUE THREAD

**Issue by danez** [stefanjudis/forrest#34]
It looked like this with 1.0.0-beta:
![bildschirmfoto 2016-07-25 um 23 06 52](https://cloud.githubusercontent.com/assets/231804/17117577/f676913c-52bc-11e6-92da-d56dd041591e.png)

**Comment by stefanjudis** [comment]
oh damn it... stupid me... sorry... :D updating the dmg's once more.

**Comment by stefanjudis** [comment]
Should be fixed by now... had a little "dreher" and didn't discover it, because it only appears once ( after that window is stored ).

I reuploaded the files in releases pane.

**Comment by danez** [comment]
thanks
