### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by sergejreznik** [stefanjudis/forrest#5]
// Change the Font-size or the let the user change it. It's really to small.
// Error-Handling if it's not a npm-project.
// Don't allow the user to scale the window to the absolute minimum.
// Why are there Developer Tools? `/view/toggle developer tools`
// Maybe let the user delete projects from project tree and not only when you're inside the project?
- Great tool, great design. Works fast and without any problems. I'm going to be happy about the final release.

My Node version is 2.15.8 on a mac.

**Comment by stefanjudis** [comment]
@sergejr 

Hey hey, thanks for feedback. 😊 

> My Node version is 2.15.8 on a mac.

But this version was correctly evaluated when you had a look into settings?

> Change the Font-size or the let the user change it. It's really to small.

Assuming only the "terminal" font-size? or the overall font-size, which I think is fine. :) 

> Maybe let the user delete projects from project tree and not only when you're inside the project?

Ja I thought about that, but didn't want to clutter the clean list view. Any recommendations?

**Comment by sergejreznik** [comment]
Hey,

/ But this version was correctly evaluated when you had a look into settings?
    - Yes.

/ Assuming only the "terminal" font-size? or the overall font-size, which I think is fine. :)
    - Only the „terminal“ font-size. Overall it’s good.

/ Maybe let the user delete projects from project tree and not only when you're inside the project?
    - Maybe use the native delete movement from right to left which known from iOS / Apple Mail for deleting projects or enable the right click event?

Best Regards,
Sergej

**Comment by stefanjudis** [comment]
> Maybe use the native delete movement from right to left which known from iOS / Apple Mail for deleting projects or enable the right click event?

Hmm... not sure about dragging. People are not used to these interactions on desktop, or?
Context menu is worth a try. 👍 

Thx.

**Comment by stefanjudis** [comment]
> Why are there Developer Tools? /view/toggle developer tools

Will keep it for now, to maybe get better user reports.

> Error-Handling if it's not a npm-project.

Will be resolved in another issue. The rest is fixed... 😎

**Comment by sergejreznik** [comment]
Okay cool, can I get the current version?

**Comment by stefanjudis** [comment]
you'll get a download link in a few min. :)
