### ISSUE TITLE
Development environment info?

### ISSUE THREAD

**Issue by rowanwins** [stefanjudis/forrest#74]
Just wondering if you could provide any info on your development environment? 

I'm using node v4.2.1 and I seem to be running into issues with the spread operators which I gather may have only been [introduced at node v5 ](https://github.com/nodejs/node/issues/3851). 

It might be worth specifying some engines in the package file if you suspect that might be a common occurance...

Cheers
Rowan

**Comment by stefanjudis** [comment]
@rowanwins 

I'm usually on the latest one ( `v6.x` ) and have rarely troubles. Will document it in `package.json` then. :)

**Comment by stefanjudis** [comment]
Hmm @rowanwins I didn't do it, or? :D
