### ISSUE TITLE
Can’t add projects

### ISSUE THREAD

**Issue by mischah** [stefanjudis/forrest#76]
I can’t add a project having a package.json containing npm scripts.

![forrest](https://cloud.githubusercontent.com/assets/441011/17776551/5eb14aaa-655d-11e6-8d49-eb57781ee343.gif)

I downloaded the latest release: Forrest-1.0.0-delta-mac.zip 

Using Mac OS X 10.11.6

:sad_panda:

**Comment by stefanjudis** [comment]
@mischah 

Okay, figured out what's the problem. I tested that carefully, but missed the fact of real initial kick off. When no config files are written.

I think you can expect a release tonight.

Sorry for inconvenience. :)

**Comment by mischah** [comment]
No problem :ok_hand:
