### ISSUE TITLE
Forrest can’t run (scripts)

### ISSUE THREAD

**Issue by mischah** [stefanjudis/forrest#78]
![forrest](https://cloud.githubusercontent.com/assets/441011/17790294/23c4e79c-6596-11e6-81a6-99c0d74fc581.gif)

Tested with:

```
node   5.5.0
npm    3.8.8
```

**Comment by stefanjudis** [comment]
Could you provide more information on how you load node? I expect nvm loading inside of your `zshrc`?

**Comment by mischah** [comment]
Update. Forrest runs after changing my environment to:

```
node   v6.4.0
npm    3.10.6
```

**Comment by mischah** [comment]
Does it need Node 6.x?

**Comment by stefanjudis** [comment]
No, that doesn't make much sense. But I'll dig into  it over the weekend. Could you still provide pieces of your zshrc? :)

Electron itself ships with node 6.x.

Did you change it temporarily or set a new nvm default?

**Comment by mischah** [comment]
I load nvm with the following two lines in my zshrc:

```
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

> Did you change it temporarily or set a new nvm default?

Nope. Its now like that:

```
$ nvm ls
       v0.10.43
        v0.12.4
        v0.12.7
         v4.2.2
         v5.1.0
         v5.2.0
         v5.4.0
         v5.5.0
         v6.0.0
         v6.2.0
->       v6.4.0
default -> node (-> v6.4.0)
node -> stable (-> v6.4.0) (default)
stable -> 6.4 (-> v6.4.0) (default)
iojs -> N/A (default)
```

Before that `v5.5.0` was the default.

**Comment by stefanjudis** [comment]
Are you sure `node` and `npm` where there when you open a new terminal session?
This is all forrest does. Starting a new terminal session and then executing commands.

maybe you're running into this nvm bug 

```
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local/Cellar/nvm/0.31.2/versions/node/v6.3.1"
Run `nvm use --delete-prefix v6.3.1 --silent` to unset it.
```

which forced me to execute this for every new sessino for a while?

**Comment by mischah** [comment]
Can’t reproduce.
